package entidades;
// Generated Mar 5, 2018 4:14:29 PM by Hibernate Tools 4.3.1



/**
 * AplicadoId generated by hbm2java
 */
public class AplicadoId  implements java.io.Serializable {


     private String cedulaOferente;
     private int idPuesto;

    public AplicadoId() {
    }

    public AplicadoId(String cedulaOferente, int idPuesto) {
       this.cedulaOferente = cedulaOferente;
       this.idPuesto = idPuesto;
    }
   
    public String getCedulaOferente() {
        return this.cedulaOferente;
    }
    
    public void setCedulaOferente(String cedulaOferente) {
        this.cedulaOferente = cedulaOferente;
    }
    public int getIdPuesto() {
        return this.idPuesto;
    }
    
    public void setIdPuesto(int idPuesto) {
        this.idPuesto = idPuesto;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AplicadoId) ) return false;
		 AplicadoId castOther = ( AplicadoId ) other; 
         
		 return ( (this.getCedulaOferente()==castOther.getCedulaOferente()) || ( this.getCedulaOferente()!=null && castOther.getCedulaOferente()!=null && this.getCedulaOferente().equals(castOther.getCedulaOferente()) ) )
 && (this.getIdPuesto()==castOther.getIdPuesto());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCedulaOferente() == null ? 0 : this.getCedulaOferente().hashCode() );
         result = 37 * result + this.getIdPuesto();
         return result;
   }   


}


