package entidades;
// Generated Mar 5, 2018 4:14:29 PM by Hibernate Tools 4.3.1

import java.sql.Date;





/**
 * CaracteristicasIncluidos generated by hbm2java
 */
public class CaracteristicasIncluidos  implements java.io.Serializable {


     private String idCaracteristicaIn;
     private int idPuestos;
     private Date fechaInclusion;

    public CaracteristicasIncluidos() {
    }

    public CaracteristicasIncluidos(int puestos, String idCaracteristicaIn, Date fechaInclusion) {
       this.idPuestos = puestos;
       this.fechaInclusion = fechaInclusion;
       this.idCaracteristicaIn = idCaracteristicaIn;
    }
   
    public String getIdCaracteristicaIn() {
        return this.idCaracteristicaIn;
    }
    
    public void setIdCaracteristicaIn(String idCaracteristicaIn) {
        this.idCaracteristicaIn = idCaracteristicaIn;
    }
    public int getidPuestos() {
        return this.idPuestos;
    }
    
    public void setidPuestos(int puestos) {
        this.idPuestos = puestos;
    }
    public Date getFechaInclusion() {
        return this.fechaInclusion;
    }
    
    public void setFechaInclusion(Date fechaInclusion) {
        this.fechaInclusion = fechaInclusion;
    }




}


