package entidades;
// Generated Mar 5, 2018 4:14:29 PM by Hibernate Tools 4.3.1

import java.sql.Date;





/**
 * HabilidadesIncluidas generated by hbm2java
 */
public class HabilidadesIncluidas  implements java.io.Serializable {


     private int idHabilidad;
     private int idServicios;
     private Date fechaInclusion;

    public HabilidadesIncluidas() {
    }

	
    public HabilidadesIncluidas(int idHabilidad) {
        this.idHabilidad = idHabilidad;
    }
    public HabilidadesIncluidas(int idHabilidad, int idServicios, Date fechaInclusion) {
       this.idHabilidad = idHabilidad;
       this.idServicios = idServicios;
       this.fechaInclusion = fechaInclusion;
    }
   
    public int getIdHabilidad() {
        return this.idHabilidad;
    }
    
    public void setIdHabilidad(int idHabilidad) {
        this.idHabilidad = idHabilidad;
    }
    public int getidServicios() {
        return this.idServicios;
    }
    
    public void setServicios(int idServicios) {
        this.idServicios = idServicios;
    }
    public Date getFechaInclusion() {
        return this.fechaInclusion;
    }
    
    public void setFechaInclusion(Date fechaInclusion) {
        this.fechaInclusion = fechaInclusion;
    }




}


