package entidades;
// Generated Mar 5, 2018 4:14:29 PM by Hibernate Tools 4.3.1



/**
 * Habilidades generated by hbm2java
 */
public class Habilidades  implements java.io.Serializable {


      private int idHabilidad;
     private String nombreHabilidad;
     private String areaTrabajo;
     private String especializacion;

    public Habilidades() {
    }

	

    public Habilidades(HabilidadesId id, String areaTrabajo, String especializacion , int idHabilidad, String nombreHabilidad) {
        
       this.areaTrabajo = areaTrabajo;
       this.especializacion = especializacion;
        this.idHabilidad = idHabilidad;
       this.nombreHabilidad = nombreHabilidad;
    }
   
   
    public String getAreaTrabajo() {
        return this.areaTrabajo;
    }
    
    public void setAreaTrabajo(String areaTrabajo) {
        this.areaTrabajo = areaTrabajo;
    }
    public String getEspecializacion() {
        return this.especializacion;
    }
    
    public void setEspecializacion(String especializacion) {
        this.especializacion = especializacion;
    }

       public int getIdHabilidad() {
        return this.idHabilidad;
    }
    
    public void setIdHabilidad(int idHabilidad) {
        this.idHabilidad = idHabilidad;
    }
    public String getNombreHabilidad() {
        return this.nombreHabilidad;
    }
    
    public void setNombreHabilidad(String nombreHabilidad) {
        this.nombreHabilidad = nombreHabilidad;
    }



}


