package entidades;
// Generated Mar 5, 2018 4:14:29 PM by Hibernate Tools 4.3.1



/**
 * PuestosPublicados generated by hbm2java
 */
public class PuestosPublicados  implements java.io.Serializable {



     private int idEmpresa;
     private int idPuestos;
     private Boolean estadoPuesto;

    public PuestosPublicados() {
    }


    public PuestosPublicados( int idEmpresa, int idPuestos, Boolean estadoPuesto) {
       
       this.idEmpresa = idEmpresa;
       this.idPuestos = idPuestos;
       this.estadoPuesto = estadoPuesto;
    }
   
    public int getidPuestos() {
        return this.idPuestos;
    }
    
    public void setidPuestos(int idPuestos) {
        this.idPuestos = idPuestos;
    }
    public int getidEmpresa() {
        return this.getidEmpresa();
    }
    
    public void setEmpresa(int empresa) {
        this.idEmpresa = empresa;
    }
    public int getPuestos() {
        return this.idPuestos;
    }
    
   
    public Boolean getEstadoPuesto() {
        return this.estadoPuesto;
    }
    
    public void setEstadoPuesto(Boolean estadoPuesto) {
        this.estadoPuesto = estadoPuesto;
    }




}


