package entidades;
// Generated Mar 5, 2018 4:14:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Puestos generated by hbm2java
 */
public class Puestos  implements java.io.Serializable {
    private Integer idPuesto;
    private Empresa empresa;
    private String nombrePuesto;
    private Float salario;
    private String descripcionPuesto;
    private Boolean tipoPublicacion; // true = publico. por el momento todos son publicos, 
                                    //  cambiar en el dao (todo lo relacionado a esta clase), Cuando 
                                    //  tengamos q dar la opcion de escoger entre privado o publico
    
//    private String ubicacion; HACE FALTA???
    private Set<PuestosPublicados> puestosPublicadoses = new HashSet<PuestosPublicados>(0);
    private Set<Aplicado> aplicados = new HashSet<Aplicado>(0);
    private Set<CaracteristicasPuestos> caracteristicasIncluidoses = new HashSet<CaracteristicasPuestos>(0);

    public Puestos() {
    }

    public Puestos(Integer idPuesto, Empresa empresa, String nombrePuesto, Float salario, String descripcionPuesto, Boolean tipoPublicacion) {
        this.idPuesto = idPuesto;
        this.empresa = empresa;
        this.nombrePuesto = nombrePuesto;
        this.salario = salario;
        this.descripcionPuesto = descripcionPuesto;
        this.tipoPublicacion = tipoPublicacion;
    }

    public Puestos(Integer idPuesto,Empresa empresa,String nombrePuesto,Float salario,String descripcionPuesto,Boolean tipoPublicacion, 
            Set<PuestosPublicados> puestosPublicadoses, Set<Aplicado> aplicados, Set<CaracteristicasPuestos> caracteristicasIncluidoses) {
        this.idPuesto = idPuesto;
        this.empresa = empresa;
        this.nombrePuesto = nombrePuesto;
        this.salario = salario;
        this.descripcionPuesto = descripcionPuesto;
        this.tipoPublicacion = tipoPublicacion;
//       this.ubicacion = ubicacion;
        this.puestosPublicadoses = puestosPublicadoses;
        this.aplicados = aplicados;
        this.caracteristicasIncluidoses = caracteristicasIncluidoses;
    }
   
    public Integer getIdPuesto() {
        return this.idPuesto;
    }
    
    public void setIdPuesto(Integer idPuesto) {
        this.idPuesto = idPuesto;
    }

    public Empresa getEmpresa() {
        return empresa;
    }

    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    
    public String getNombrePuesto() {
        return this.nombrePuesto;
    }
    
    public void setNombrePuesto(String nombrePuesto) {
        this.nombrePuesto = nombrePuesto;
    }
    public Float getSalario() {
        return this.salario;
    }
    
    public void setSalario(Float salario) {
        this.salario = salario;
    }
    public String getDescripcionPuesto() {
        return this.descripcionPuesto;
    }
    
    public void setDescripcionPuesto(String descripcionPuesto) {
        this.descripcionPuesto = descripcionPuesto;
    }
    
    public Boolean getTipoPublicacion() {
        return tipoPublicacion;
    }

    public void setTipoPublicacion(Boolean tipoPublicacion) {
        this.tipoPublicacion = tipoPublicacion;
    }
    
    public Set<PuestosPublicados> getPuestosPublicadoses() {
        return this.puestosPublicadoses;
    }
    
    public void setPuestosPublicadoses(Set<PuestosPublicados> puestosPublicadoses) {
        this.puestosPublicadoses = puestosPublicadoses;
    }
    public Set<Aplicado> getAplicados() {
        return this.aplicados;
    }
    
    public void setAplicados(Set<Aplicado> aplicados) {
        this.aplicados = aplicados;
    }
    public Set<CaracteristicasPuestos> getCaracteristicasIncluidoses() {
        return this.caracteristicasIncluidoses;
    }
    
    public void setCaracteristicasIncluidoses(Set<CaracteristicasPuestos> caracteristicasIncluidoses) {
        this.caracteristicasIncluidoses = caracteristicasIncluidoses;
    }




}


