package entidades;
// Generated Mar 5, 2018 4:14:29 PM by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.List;




/**
 * Puestos generated by hbm2java
 */
public class Puestos  implements java.io.Serializable {
    private Integer idPuesto;
    private Empresa empresa;
    private String nombrePuesto;
    private Float salario;
    private String descripcionPuesto;
    private Boolean tipoPublicacion; // true = publico. por el momento todos son publicos, 
//    private String ubicacion; HACE FALTA???
    private Boolean activo; // true =  esta activo cuando se agrega es activo automaticamente
    private List<CaracteristicasPuestos> caracteristicasPuestos = new ArrayList();

    public Puestos() {
        
    }

    public Puestos(Integer idPuesto, Empresa empresa, String nombrePuesto, Float salario, String descripcionPuesto, Boolean tipoPublicacion) {
        this.idPuesto = idPuesto;
        this.empresa = empresa;
        this.nombrePuesto = nombrePuesto;
        this.salario = salario;
        this.descripcionPuesto = descripcionPuesto;
        this.tipoPublicacion = tipoPublicacion;
    }

    public Puestos(Integer idPuesto,Empresa empresa,String nombrePuesto,Float salario,String descripcionPuesto,Boolean tipoPublicacion, List<CaracteristicasPuestos> caracteristicasPuestos) {
        this.idPuesto = idPuesto;
        this.empresa = empresa;
        this.nombrePuesto = nombrePuesto;
        this.salario = salario;
        this.descripcionPuesto = descripcionPuesto;
        this.tipoPublicacion = tipoPublicacion;
//       this.ubicacion = ubicacion;
        this.caracteristicasPuestos = caracteristicasPuestos;
    }
   
    public Integer getIdPuesto() {
        return this.idPuesto;
    }
    
    public void setIdPuesto(Integer idPuesto) {
        this.idPuesto = idPuesto;
    }

    public Empresa getEmpresa() {
        return empresa;
    }

    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    
    public String getNombrePuesto() {
        return this.nombrePuesto;
    }
    
    public void setNombrePuesto(String nombrePuesto) {
        this.nombrePuesto = nombrePuesto;
    }
    public Float getSalario() {
        return this.salario;
    }
    
    public void setSalario(Float salario) {
        this.salario = salario;
    }
    public String getDescripcionPuesto() {
        return this.descripcionPuesto;
    }
    
    public void setDescripcionPuesto(String descripcionPuesto) {
        this.descripcionPuesto = descripcionPuesto;
    }
    
    public Boolean getTipoPublicacion() {
        return tipoPublicacion;
    }

    public void setTipoPublicacion(Boolean tipoPublicacion) {
        this.tipoPublicacion = tipoPublicacion;
    }

    public Boolean getActivo() {
        return activo;
    }

    public void setActivo(Boolean activo) {
        this.activo = activo;
    }
    
    public List<CaracteristicasPuestos> getCaracteristicasPuestos() {
        return this.caracteristicasPuestos;
    }
    
    public void setCaracteristicasPuestos (List<CaracteristicasPuestos> caracteristicasPuestos) {
        this.caracteristicasPuestos = caracteristicasPuestos;
    }




}


