package entidades;
// Generated Mar 5, 2018 4:14:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Puestos generated by hbm2java
 */
public class Puestos  implements java.io.Serializable {


     private Integer idPuesto;
     private String nombrePuesto;
     private Float salario;
     private String descripcionPuesto;
     private String ubicacion;
     private Set<PuestosPublicados> puestosPublicadoses = new HashSet<PuestosPublicados>(0);
     private Set<Aplicado> aplicados = new HashSet<Aplicado>(0);
     private Set<CaracteristicasIncluidos> caracteristicasIncluidoses = new HashSet<CaracteristicasIncluidos>(0);

    public Puestos() {
    }

    public Puestos(String nombrePuesto, Float salario, String descripcionPuesto, String ubicacion, Set<PuestosPublicados> puestosPublicadoses, Set<Aplicado> aplicados, Set<CaracteristicasIncluidos> caracteristicasIncluidoses) {
       this.nombrePuesto = nombrePuesto;
       this.salario = salario;
       this.descripcionPuesto = descripcionPuesto;
       this.ubicacion = ubicacion;
       this.puestosPublicadoses = puestosPublicadoses;
       this.aplicados = aplicados;
       this.caracteristicasIncluidoses = caracteristicasIncluidoses;
    }
   
    public Integer getIdPuesto() {
        return this.idPuesto;
    }
    
    public void setIdPuesto(Integer idPuesto) {
        this.idPuesto = idPuesto;
    }
    public String getNombrePuesto() {
        return this.nombrePuesto;
    }
    
    public void setNombrePuesto(String nombrePuesto) {
        this.nombrePuesto = nombrePuesto;
    }
    public Float getSalario() {
        return this.salario;
    }
    
    public void setSalario(Float salario) {
        this.salario = salario;
    }
    public String getDescripcionPuesto() {
        return this.descripcionPuesto;
    }
    
    public void setDescripcionPuesto(String descripcionPuesto) {
        this.descripcionPuesto = descripcionPuesto;
    }
    public String getUbicacion() {
        return this.ubicacion;
    }
    
    public void setUbicacion(String ubicacion) {
        this.ubicacion = ubicacion;
    }
    public Set<PuestosPublicados> getPuestosPublicadoses() {
        return this.puestosPublicadoses;
    }
    
    public void setPuestosPublicadoses(Set<PuestosPublicados> puestosPublicadoses) {
        this.puestosPublicadoses = puestosPublicadoses;
    }
    public Set<Aplicado> getAplicados() {
        return this.aplicados;
    }
    
    public void setAplicados(Set<Aplicado> aplicados) {
        this.aplicados = aplicados;
    }
    public Set<CaracteristicasIncluidos> getCaracteristicasIncluidoses() {
        return this.caracteristicasIncluidoses;
    }
    
    public void setCaracteristicasIncluidoses(Set<CaracteristicasIncluidos> caracteristicasIncluidoses) {
        this.caracteristicasIncluidoses = caracteristicasIncluidoses;
    }




}


