package entidades;
// Generated Mar 5, 2018 4:14:29 PM by Hibernate Tools 4.3.1



/**
 * ServiciosPublicados generated by hbm2java
 */
public class ServiciosPublicados  implements java.io.Serializable {


    
     private Boolean estadoServicio;
      private int idServicio;
     private String cedulaOferente;

    public ServiciosPublicados() {
    }

    public ServiciosPublicados(ServiciosPublicadosId id, Oferente oferente, Servicios servicios, Boolean estadoServicio, int idServicio, String cedulaOferente) {
   
        this.estadoServicio = estadoServicio;
        this.idServicio = idServicio;
        this.cedulaOferente = cedulaOferente;
    }

    
    
	
    

    public int getIdServicio() {
        return idServicio;
    }

    public void setIdServicio(int idServicio) {
        this.idServicio = idServicio;
    }

    public String getCedulaOferente() {
        return cedulaOferente;
    }

    public void setCedulaOferente(String cedulaOferente) {
        this.cedulaOferente = cedulaOferente;
    }
    
    
   
    public Boolean getEstadoServicio() {
        return this.estadoServicio;
    }
    
    public void setEstadoServicio(Boolean estadoServicio) {
        this.estadoServicio = estadoServicio;
    }




}


