package entidades;
// Generated Mar 5, 2018 4:14:29 PM by Hibernate Tools 4.3.1



/**
 * ServiciosPublicadosId generated by hbm2java
 */
public class ServiciosPublicadosId  implements java.io.Serializable {


     private int idServicio;
     private String cedulaOferente;

    public ServiciosPublicadosId() {
    }

    public ServiciosPublicadosId(int idServicio, String cedulaOferente) {
       this.idServicio = idServicio;
       this.cedulaOferente = cedulaOferente;
    }
   
    public int getIdServicio() {
        return this.idServicio;
    }
    
    public void setIdServicio(int idServicio) {
        this.idServicio = idServicio;
    }
    public String getCedulaOferente() {
        return this.cedulaOferente;
    }
    
    public void setCedulaOferente(String cedulaOferente) {
        this.cedulaOferente = cedulaOferente;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ServiciosPublicadosId) ) return false;
		 ServiciosPublicadosId castOther = ( ServiciosPublicadosId ) other; 
         
		 return (this.getIdServicio()==castOther.getIdServicio())
 && ( (this.getCedulaOferente()==castOther.getCedulaOferente()) || ( this.getCedulaOferente()!=null && castOther.getCedulaOferente()!=null && this.getCedulaOferente().equals(castOther.getCedulaOferente()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdServicio();
         result = 37 * result + ( getCedulaOferente() == null ? 0 : this.getCedulaOferente().hashCode() );
         return result;
   }   


}


